### ISSUE TITLE
`route.path` is not editable in extendRoute

### ISSUE THREAD

**Issue by PindaPixel** [posva/unplugin-vue-router#518] opened 2024-09-27 11:48 UTC
Regarding https://github.com/posva/unplugin-vue-router/discussions/468#discussioncomment-10243690

When editing `route.path`, the path stays unchanged.

This causes https://github.com/posva/unplugin-vue-router/discussions/468#discussioncomment-10243694 to still occur

e.g.:
```typescript
extendRoute(route) 
{
    console.log(route.path); // "question/:q-id"
    route.path = "question/:qId";
    console.log(route.path); // still "question/:q-id"
}
```

Edit:
I just saw https://github.com/posva/unplugin-vue-router/blob/main/src/core/extendRoutes.ts#L144, adding a leading slash would break my route hierarchy.

**Comment by posva** [comment] 2024-09-27 14:14
Duplicate of #341

**Closed by posva** 2024-09-27 14:14 UTC
