### ISSUE TITLE
definePage doesn't work with webpack

### ISSUE THREAD

**Issue by tzhh0617** [posva/unplugin-vue-router#223] opened 2023-08-30 03:46 UTC
```
<template>
  <div>
  </div>
</template>

<script lang="ts" setup>
definePage({
  name: 'IndexPage'
})
</script>
```

```
 error  in ./src/pages/index.vue?definePage&vue

Module Error (from ./node_modules/.pnpm/vue-loader@17.2.2_vue@3.3.4_webpack@5.88.1/node_modules/vue-loader/dist/index.js):
At least one <template> or <script> is required in a single file component.
```

error demo：
https://github.com/tzhh0617/vue3-template

**Comment by posva** [comment] 2023-08-30 06:26
Duplicate of https://github.com/posva/unplugin-vue-router/issues/163

**Closed by posva** 2023-08-30 06:26 UTC
