### ISSUE TITLE
Vite HMR circular dependancies

### ISSUE THREAD

**Issue by demyte** [posva/unplugin-vue-router#309] opened 2024-02-13 08:28 UTC
Hi there,

With vite 5.x, I am getting circular imports with this plugin on any page I use `useRouter()` or `useRoute()` 

For example:
```
 vite:hmr [file change] src/components/AddinFooter.vue +4s
  vite:hmr [vue:update(template)] D:/xpna/main/src/xpna.addin.client/src/components/AddinFooter.vue +10m
  vite:hmr circular imports detected: /src/components/AddinFooter.vue -> virtual:vue-router/auto -> virtual:vue-router/auto/routes -> /src/pages/addin.vue -> /src/components/AddinFooter.vue +19ms
6:21:46 pm [vite] page reload src/components/AddinFooter.vue (circular imports)
```

Is there anyway to stop this happening as at dev time its causing page reloads instead of HMR updates?

In my `vite.config` plugins I am using  

VueRouter:
```
import VueRouter from 'unplugin-vue-router/vite'
....
plugins: [
  VueRouter({})
...
]
....
```

AutoImports:

```
import { VueRouterAutoImports } from 'unplugin-vue-router'
....
plugins: [
  AutoImport({
    imports: [VueRouterAutoImports]
  }),
...
]
....
```

**Comment by posva** [comment] 2024-02-13 09:29
Duplicate of #132

**Closed by posva** 2024-02-13 09:29 UTC
