### ISSUE TITLE
Redirect not works

### ISSUE THREAD

**Issue by mazlum** [posva/unplugin-vue-router#64] opened 2022-09-13 14:00 UTC
```
<route lang="yaml">
redirect:
  name: Root
</route>
```

Redirect not works with route tag.

**Comment by posva** [comment] 2022-09-13 14:46
Duplicate of https://github.com/posva/unplugin-vue-router/discussions/63#discussioncomment-3632637

**Closed by posva** 2022-09-13 14:46 UTC
