### ISSUE TITLE
route not support vite hmr

### ISSUE THREAD

**Issue by bobby169** [posva/unplugin-vue-router#333] opened 2024-03-03 06:38 UTC
```
<route lang="json">
{
  "layout": "basic"
}
</route>
```

When I add the <route> custom block, it doesn't work with vite dev; I have to run `npm run dev` for it to work.

**Comment by posva** [comment] 2024-03-03 07:49
Duplicate of #292

**Closed by posva** 2024-03-03 07:49 UTC
