### ISSUE TITLE
RangeError: Maximum call stack size exceeded error when using data loader with lazy option

### ISSUE THREAD

**Issue by CodeInKlingon** [posva/unplugin-vue-router#237] opened 2023-09-27 23:37 UTC
I am encountering RangeError: Maximum call stack size exceeded when using loaders with the lazy flag.
If I remove the lazy option for the two loaders the issue goes away.

![image](https://github.com/posva/unplugin-vue-router/assets/9805593/0cf058f6-3ea9-424a-b528-0517315587d5)

Repro Link: https://stackblitz.com/edit/vitejs-vite-bnwqej?file=src%2Fpages%2Fseason%2F%5BseasonId%5D.vue

loaders are in:
```src/pages/season/[seasonId].vue``` & ```src/pages/season/[seasonId]/registration/[submissionId].vue```

Repro Steps:
approach 1:
- After the dev server starts navigate through the demo app:
- login -> under Completed Registrations click season 1 -> wait for load -> click back to landing -> under Completed Registrations click season 2
- this consistantly breaks for me

aproach 2 (multiple loaders):
- After the dev server starts navigate through the demo app:
  - login
  - under Inprogress Registrations click Season 1
  - wait for load on both loaders (2s)
  - click back to landing 
  - under Inprogress Registrations click season 2
  - you may encounter the same error here. If not
  - repeat a few times
- this eventually breaks for me

**Comment by posva** [comment] 2023-09-28 06:29
Duplicate of https://github.com/posva/unplugin-vue-router/issues/173

**Closed by posva** 2023-09-28 06:29 UTC
