### ISSUE TITLE
How to add set parent route's meta?

### ISSUE THREAD

**Issue by carrypann** [posva/unplugin-vue-router#388] opened 2024-05-20 08:26 UTC
Consider the following folder structure:
```
src/pages/
├── users/
    └── index.vue

```
will generate the following routes:
```
const routes = [
  {
    path: '/users',
    // how to set meta here?
    children: [
      { path: '', component: () => import('src/pages/users/index.vue') },
    ],
  },
]
```
Is there any way to set parent route `/users` meta info?

**Comment by posva** [comment] 2024-05-20 08:35
Duplicate of #33

**Closed by posva** 2024-05-20 08:35 UTC
